plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    id("me.modmuss50.mod-publish-plugin") version "1.1.0"
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
    version = getFullModVersion()
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
    withSourcesJar()
}

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {

    mappings channel: mapping_channel, version: mapping_version
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    copyIdeResources = true

    runs {
        // applies to all the run configs below
        configureEach {
            workingDirectory project.file('run')

            arg "-mixin.config=" + "${mod_id}" + ".mixins.json"

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')

            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "${mod_id}" + '.mixin-refmap.json'
    config "${mod_id}" + '.mixins.json'
}

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    flatDir {
        dir 'libs'
    }

    exclusiveContent {
        forRepository { maven { url "https://echoellet.github.io/Controlify/" } }
        forRepositories(fg.repository)
        filter { includeGroup "dev.echoellet" }
    }
    exclusiveContent {
        forRepository { maven { name = "Modrinth"; url = "https://api.modrinth.com/maven" } }
        forRepositories(fg.repository)
        filter { includeGroup "maven.modrinth" }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
//    dependencies {
//        compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
//        implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0")) {
//            jarJar.ranged(it, "[0.5.0,)")
//        }
//    }
    implementation fg.deobf("maven.modrinth:epic-fight:${epicfight_version}")
    implementation fg.deobf("maven.modrinth:epic-fight-skill-tree:${epicskills_version}")
    implementation fg.deobf("maven.modrinth:epic-fight-invincible-lib:${invincible_lib_version}")

    implementation fg.deobf("curse.maven:epic-fight-avalon-1268823:7058350")
    implementation fg.deobf("curse.maven:mmmmmmmmmmmm-225738:6237015")
    implementation fg.deobf("curse.maven:selene-499980:6283242")
    implementation fg.deobf("curse.maven:sophisticated-core-618298:6266807")
    implementation fg.deobf("curse.maven:sophisticated-backpacks-422301:6246607")
    compileOnly fg.deobf("curse.maven:armourers-workshop-229523:6965580")//唯一真神

    compileOnly fg.deobf("curse.maven:shoulder-surfing-reloaded-243190:6993788")
//    implementation fg.deobf("curse.maven:embeddium-908741:5681725")
//    implementation fg.deobf("curse.maven:oculus-581495:6020952")
    implementation fg.deobf("curse.maven:xaeros-world-map-317780:6538337")

    compileOnly fg.deobf("dev.echoellet:controlify-forgified:${project.controlify_version}")
    runtimeOnly fg.deobf("maven.modrinth:yacl:3.6.6+1.20.1-forge") // Required to run Controlify (transitive dependency)
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version       : forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors         : mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : "${mod_id}" + ".mixins.json"
        ])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

def getFullModVersion() {
    return "${mod_version}-mc${minecraft_version}-forge"
}

publishMods {
    def releaseNotesFile = project.file("RELEASE_NOTES.md")
    def releaseNotesContent = releaseNotesFile.text

    changelog = """
|**Tested against:**
|- **Forge:** ${forge_version}
|- **Minecraft:** ${minecraft_version}
|- **Epic Fight:** ${epicfight_version}
|- **Epic Fight - Invincible Lib:** ${invincible_lib_version}
|- **Epic Fight: Skill Tree:** ${epicskills_version}
|
|${releaseNotesContent}
""".stripMargin().trim()

    modLoaders.add("forge")
    type = STABLE
    displayName = getFullModVersion()
    file = tasks.jar.archiveFile

    curseforge {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        projectId = "1011068"
        minecraftVersions.add(minecraft_version)
        projectSlug = "sword-soaring"

        requires("epic-fight-mod")
        requires("epic-fight-invincible")
    }

    modrinth {
        accessToken = System.getenv("MODRINTH_TOKEN")
        projectId = "oP1of4Wn"
        minecraftVersions.add(minecraft_version)

        requires("epic-fight")
        requires("epic-fight-invincible-lib")

        // Syncs the GitHub README with the Modrinth project description
        // projectDescription = file("README.md").text
    }
}
